### ISSUE TITLE
USB transport not working

### ISSUE THREAD

**Issue by JeffLIrion** [JeffLIrion/adb_shell#117]
### Description

> I'm having a bit of trouble with your adb shell for python.
>
> Despite installing using the 'pip install adb-shell[usb]' command, I am getting the transport error and it's telling me to install the package in the same way.
>
> Do you have any idea what's wrong?

### Log

No logs available

**Comment by JeffLIrion** [comment]
Please see the discussion in this issue, and the linked comment in particular: https://github.com/JeffLIrion/adb_shell/issues/114#issuecomment-664639741

**Comment by ajuancer** [comment]
A note about the last step that maybe you're missing: import the DLL file before requesting it:
```python
os.add_dll_directory("YOUR_PATH")
from adb_shell.transport.usb_transport import UsbTransport
```
If you try to import the `UsbTransport` after the DLL, you will get:
```python
FileNotFoundError: Could not find module 'libusb-1.0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by 5picoseconds** [comment]
so far, this is what I have

`import os`
`os.add_dll_directory('C:\\Users\\Public\\Documents\\libusb-1.0.dll')`
`from adb_shell.transport.usb_transport import UsbTransport`
`from adb_shell.adb_device import AdbDeviceTcp, AdbDeviceUsb`
`from adb_shell.auth.sign_pythonrsa import PythonRSASigner
`
and it gives me this log:
C:\Users\stefan.pompilio\PhoneTestingAdb\venv\Scripts\python.exe C:/Users/stefan.pompilio/PhoneTestingAdb/main.py
Traceback (most recent call last):
  File "C:/Users/stefan.pompilio/PhoneTestingAdb/main.py", line 3, in <module>
    from adb_shell.transport.usb_transport import UsbTransport
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 59, in <module>
    import usb1
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\libusb1.py", line 192, in <module>
    libusb = _loadLibrary()
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\libusb1.py", line 166, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "C:\Users\stefan.pompilio\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libusb-1.0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by JeffLIrion** [comment]
Sanity check:

```python
import os
import sys

print(os.path.exists('C:\\Users\\Public\\Documents\\libusb-1.0.dll'))
print(sys.version)
```

**Comment by 5picoseconds** [comment]
This gives me:


C:\Users\stefan.pompilio\PhoneTestingAdb\venv\Scripts\python.exe C:/Users/stefan.pompilio/PhoneTestingAdb/main.py
True
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)]

Process finished with exit code 0

**Comment by JeffLIrion** [comment]
It looks like you're supposed to add the path of the directory containing the .dll file, not the path to the .dll file itself.

**Comment by 5picoseconds** [comment]
Hmmm... well it's a different error now (the same one that ajauncer has at the end that he fixed with killing the server). I could have sworn I started with that! maybe I had something else broken and I fixed it and forgot? 

Either way, thank you two for all the help!!!!

**Comment by 5picoseconds** [comment]
Actually one more thing before I head back, what ID do I use for AdbDeviceUsb?

**Comment by JeffLIrion** [comment]
Try what I wrote in the second paragraph here: https://github.com/JeffLIrion/adb_shell/issues/114#issuecomment-664451936

**Comment by 5picoseconds** [comment]
Apologies for the late response,

after ironing out some of the kinks, this is the new error with the program.

````
Traceback (most recent call last):
  File "C:/Users/stefan.pompilio/PhoneTestingAdb/main.py", line 20, in <module>
    device = AdbDeviceUsb(transport)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\adb_device.py", line 1205, in __init__
    transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 620, in find_adb
    return cls._find(
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 507, in _find
    return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 597, in _find_first
    return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s))
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 565, in _find_devices
    if device_matcher is None or device_matcher(transport):
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 470, in <lambda>
    return lambda device: device.serial_number == serial
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\transport\usb_transport.py", line 410, in serial_number
    return self._device.getSerialNumber()
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\__init__.py", line 2136, in getSerialNumber
    return self.open().getSerialNumber()
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\__init__.py", line 2171, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\usb1\__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNotSupported: LIBUSB_ERROR_NOT_SUPPORTED [-12]
````

Have any ideas with what to do here?
I know it gets the correct serial number so I'm not sure why it's yelling at me this time.

**Comment by 5picoseconds** [comment]
just did another test opening adbkey.pub instead of adbkey and I get this error instead

````
Traceback (most recent call last):
  File "C:/Users/stefan.pompilio/PhoneTestingAdb/main.py", line 17, in <module>
    signer = PythonRSASigner('', priv)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\auth\sign_pythonrsa.py", line 141, in __init__
    self.priv_key = _load_rsa_private_key(priv)
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\adb_shell\auth\sign_pythonrsa.py", line 108, in _load_rsa_private_key
    der = rsa.pem.load_pem(pem, 'PRIVATE KEY')
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\rsa\pem.py", line 101, in load_pem
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\rsa\pem.py", line 101, in <listcomp>
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "C:\Users\stefan.pompilio\PhoneTestingAdb\venv\lib\site-packages\rsa\pem.py", line 75, in _pem_lines
    raise ValueError('No PEM start marker "%r" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN PRIVATE KEY-----'" found

Process finished with exit code 1
````

I'm pretty sure this one is closer to correct

**Comment by ajuancer** [comment]
According to [this issue](https://github.com/google/python-adb/issues/99) the project from which this wrapper is derived from, [python-adb](https://github.com/google/python-adb), fixed this issue [here](https://github.com/google/python-adb/blob/master/adb/common.py#L120). This exception is also in Jeff's [adb_shell](https://github.com/JeffLIrion/adb_shell/blob/8682fb7bba31e7cf7a07e26382e1b80b09633dd4/adb_shell/transport/usb_transport.py#L342). 
Maybe you can try with [this solution](https://stackoverflow.com/a/17350543/11688263).

**Comment by 5picoseconds** [comment]
@ajuancer I tried the other solution (using zadig) and it didn't seem to work (I think drivers are properly installed so replacing them does nothing)
How would I go about adding the exception to my code? 
Apologies for sounding dumb, I'm still a novice with python

**Comment by ajuancer** [comment]
can you share the code snippet that is causing the previous [log](https://github.com/JeffLIrion/adb_shell/issues/117#issuecomment-674786729)?
also note that if the issue `USB transport not working` is solved, maybe you should start a new one.
***
pd: there're no dumb questions!

**Comment by JeffLIrion** [comment]
@ajuancer you got ADB over USB to work on Windows, right? You closed your issue so I assume you got it working.

**Comment by 5picoseconds** [comment]
> also note that if the issue `USB transport not working` is solved, maybe you should start a new one.

This is a good point, I have now opened a new issue for this named Libusb error, [issue #118](https://github.com/JeffLIrion/adb_shell/issues/118)

**Comment by ajuancer** [comment]
> 
> 
> @ajuancer you got ADB over USB to work on Windows, right? You closed your issue so I assume you got it working.

yes, all working fine. Issue #114 was the only problem I had while implementing the ADB through USB

**Comment by ajuancer** [comment]
> This is a good point, I have now opened a new issue for this named Libusb error, issue #118

okay, let's continue there 😄 
@JeffLIrion maybe this issue should be closed
