### ISSUE TITLE
"Empty" messages incorrectly send empty bulk_writes, which breaks the USB transport

### ISSUE THREAD

**Issue by baconwaifu** [JeffLIrion/adb_shell#127]
### Description

Calling `_send()` on a message with an empty data field sends a spurious USB write that confuses ADB. This may actually have exposed a bug in *adb*, but it's trivial enough to workaround here.

It's somewhat surprising that this wasn't already caught, because this breaks *any* multi-packet operations over USB on affected versions of adb.

### Log

```
DEBUG:adb_shell.adb_device:bulk_write: b'OKAY\x01\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\xb4\xbe\xa6'
DEBUG:adb_shell.adb_device:bulk_write: b''
<REDACTED>
Traceback (most recent call last):
File "/home/<redacted>/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line 278, in bulk_read
return bytes(self._transport.bulkRead(self._read_endpoint, numbytes, timeout=self._timeout_ms(transport_timeout_s)))                                                                                             File "/home/<redacted>/.local/lib/python3.8/site-packages/usb1/__init__.py", line 1569, in bulkRead
transferred = self._bulkTransfer(endpoint, data, length, timeout)
File "/home/<redacted>/.local/lib/python3.8/site-packages/usb1/__init__.py", line 1517, in _bulkTransfer
mayRaiseUSBError(libusb1.libusb_bulk_transfer(
File "/home/<redacted>/.local/lib/python3.8/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
__raiseUSBError(value) 
File "/home/<redacted>/.local/lib/python3.8/site-packages/usb1/__init__.py", line 125, in raiseUSBError
raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]
```

Solution/Workaround:
add an `if len(msg.data) > 0:` check to `_send` so it doesn't "send" the data component if there's no data (too lazy to fork and PR for one line)

**Comment by JeffLIrion** [comment]
I opened a pull request to fix this. Please test it and make sure it doesn't break the TCP transport. 

https://github.com/JeffLIrion/adb_shell/pull/128
