### ISSUE TITLE
Issue in connecting adb over usb

### ISSUE THREAD

**Issue by cyy60rg** [JeffLIrion/adb_shell#194]
Traceback (most recent call last):
  File "/home/**********/main.py", line 16, in <module>
    device.connect(rsa_keys=[signer], auth_timeout_s=10)
  File "/home/**********//venv/lib/python3.8/site-packages/adb_shell/adb_device.py", line 649, in connect
    self._available, self._maxdata = self._io_manager.connect(self._banner, rsa_keys, auth_timeout_s, auth_callback, adb_info)
  File "/home/**********//venv/lib/python3.8/site-packages/adb_shell/adb_device.py", line 195, in connect
    self._transport.connect(adb_info.transport_timeout_s)
  File "/home/**********//venv/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line 230, in connect
    assert read_endpoint is not None
AssertionError

**Comment by irezwi** [comment]
I've also experienced this issue when running example code. Let me know if I can provide any debugging info.

**Comment by maybe-sybr** [comment]
I typoed your handle above @JeffLIrion , so just pinging again to make sure you get an email for this thread :)

**Comment by cyy60rg** [comment]
Hi team,

The error is fixed
 I am struggling with another error.

Traceback (most recent call last):
  File "/home/../main.py", line 21, in <module>
    device.connect(rsa_keys=[signer], auth_timeout_s=0.1)
  File "/home/../venv/lib/python3.8/site-packages/adb_shell/adb_device.py", line 649, in connect
    self._available, self._maxdata = self._io_manager.connect(self._banner, rsa_keys, auth_timeout_s, auth_callback, adb_info)
  File "/home/../venv/lib/python3.8/site-packages/adb_shell/adb_device.py", line 195, in connect
    self._transport.connect(adb_info.transport_timeout_s)
  File "/home/../venv/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line 254, in connect
    self._transport.claimInterface(self._interface_number)
  File "/home/../venv/lib/python3.8/site-packages/usb1/__init__.py", line 1147, in claimInterface
    mayRaiseUSBError(
  File "/home/../venv/lib/python3.8/site-packages/usb1/__init__.py", line 128, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/../venv/lib/python3.8/site-packages/usb1/__init__.py", line 120, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]

am I doing something wrong?
I have used the same code present in the readme

**Comment by JeffLIrion** [comment]
@cyy60rg please open a new issue. I'm going to close this one.

**Comment by daniellee630911** [comment]
> 
Hi @cyy60rg 
Do you fixed this issue?
I'm facing same issue now.

Thanks,

Daniel
