### ISSUE TITLE
How can I get access to the device with password to adb?

### ISSUE THREAD

**Issue by cmbs2019** [JeffLIrion/adb_shell#218]
Thanks for your performance work.
I have a device, using mdm9607 , when connect to it via adb , the user(root) and password must be given to it.
It doesn't have adb key.
When I use adb_shell via python to connect it , my system will down.
How can I get the access , thanks.

**Comment by TheZ3ro** [comment]
can you send a screenshot or describe better how do you connect with a user and password? this is not a common type of authentication in adb.
also if you could intercept USB or TCP communication with Wireshark would greatly help.

**Comment by cmbs2019** [comment]
Thanks for your reply. This device can connect with password like this.
![image](https://github.com/JeffLIrion/adb_shell/assets/47133778/315d6670-43c1-4d24-9746-a0bf87c3d57a)
Using user as 'root', and password as 'oelinux123'.

**Comment by TheZ3ro** [comment]
what if you use adb_shell like this?

```python
from adb_shell.adb_device import AdbDeviceUsb
from adb_shell.auth.sign_pythonrsa import PythonRSASigner

# Load the public and private keys
adbkey = 'path/to/adbkey'
with open(adbkey) as f:
    priv = f.read()
with open(adbkey + '.pub') as f:
     pub = f.read()
signer = PythonRSASigner(pub, priv)

# Connect via USB (package must be installed via `pip install adb-shell[usb])`
device = AdbDeviceUsb()
device.connect(rsa_keys=[signer], auth_timeout_s=0.1)

# Send a shell command
login = 'root\noelinux123\n'
response = device.shell(login + 'whoami')
```

**Comment by cmbs2019** [comment]
Thank you . I try it, but doesn't work.
Since I don't have adbkey, I use the function below
`device = AdbDeviceTcp('127.0.0.1', 5037, default_transport_timeout_s=9.)
        device.connect(auth_timeout_s=0.1)
        login = 'root\noelinux123\n'
        response = device.shell(login + 'whoami')`
But cannot connect.
`Traceback (most recent call last):
  File "E:\Project\PyOneDark\main.py", line 5974, in adb_connect
    device.connect(auth_timeout_s=0.1)
  File "E:\Project\PyOneDark\venv\lib\site-packages\adb_shell\adb_device.py", line 675, in connect
    self._available, self._maxdata = self._io_manager.connect(self._banner, rsa_keys, auth_timeout_s, auth_callback, adb_info)
  File "E:\Project\PyOneDark\venv\lib\site-packages\adb_shell\adb_device.py", line 228, in connect
    cmd, arg0, maxdata, banner2 = self._read_expected_packet_from_device([constants.AUTH, constants.CNXN], adb_info)
  File "E:\Project\PyOneDark\venv\lib\site-packages\adb_shell\adb_device.py", line 408, in _read_expected_packet_from_device
    cmd, arg0, arg1, data = self._read_packet_from_device(adb_info)
  File "E:\Project\PyOneDark\venv\lib\site-packages\adb_shell\adb_device.py", line 486, in _read_packet_from_device
    msg = self._read_bytes_from_device(constants.MESSAGE_SIZE, adb_info)
  File "E:\Project\PyOneDark\venv\lib\site-packages\adb_shell\adb_device.py", line 455, in _read_bytes_from_device
    raise exceptions.AdbTimeoutError("Timeout: read {} of {} bytes (transport_timeout_s = {}, read_timeout_s = {})".format(len(data), len(data) + length, adb_info.transport_timeout_s, adb_info.read_timeout_s))
adb_shell.exceptions.AdbTimeoutError: Timeout: read 0 of 24 bytes (transport_timeout_s = 9.0, read_timeout_s = 10.0)`

**Comment by cmbs2019** [comment]
I use this method and it works, but some command like 'ls' or 'sqlite3' doesn't support.
`    def adb_connect(self):
        # 连接设备
        self.child = pexpect.popen_spawn.PopenSpawn('adb shell')

        # 匹配提示符，输入用户名和密码
        self.child.expect(['#', ' $', 'mdm9607 login:'], timeout=3)
        self.adb_out.insertPlainText('检测到登录请求...\n')
        self.child.sendline('root')
        self.adb_out.insertPlainText('发送root用户名...\n')
        time.sleep(1)
        self.child.expect(['#', ' $', 'Password:'], timeout=4)
        self.adb_out.insertPlainText('检测到密码请求...\n')
        self.child.send('oelinux123\n')
        self.adb_out.insertPlainText('输入密码...\n')
        self.child.expect(['#', '~'], timeout=3)
        self.adb_out.insertPlainText('登录成功\n')`
