### ISSUE TITLE
Home Assistant Android TV error

### ISSUE THREAD

**Issue by JeffLIrion** [JeffLIrion/adb_shell#53]
From https://community.home-assistant.io/t/native-support-for-android-tv-android-devices/82792/356

```
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_manager] Sending command to 192.168.1.38:5555 via adb-shell: (dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'OPEN\x01\x00\x00\x00\x00\x00\x00\x00\r\x02\x00\x00>\xa8\x00\x00\xb0\xaf\xba\xb1'
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b"shell:(dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)\x00"
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_read(24): b'OKAYp\t\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\xb4\xbe\xa6'
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_read(24): b'CLSEp\t\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbc\xb3\xac\xba'
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'CLSE\x01\x00\x00\x00p\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbc\xb3\xac\xba'
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b''
2019-12-04 12:02:42 DEBUG (SyncWorker_7) [custom_components.androidtv.androidtv.firetv] Fire TV 192.168.1.38:5555 `get_properties` response: 
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_manager] Sending command to 192.168.1.38:5555 via adb-shell: (dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'OPEN\x01\x00\x00\x00\x00\x00\x00\x00\r\x02\x00\x00>\xa8\x00\x00\xb0\xaf\xba\xb1'
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b"shell:(dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)\x00"
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_read(24): b'OKAYq\t\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\xb4\xbe\xa6'
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_read(24): b'CLSEq\t\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbc\xb3\xac\xba'
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'CLSE\x01\x00\x00\x00q\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbc\xb3\xac\xba'
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b''
2019-12-04 12:02:53 DEBUG (SyncWorker_2) [custom_components.androidtv.androidtv.firetv] Fire TV 192.168.1.38:5555 `get_properties` response: 
2019-12-04 12:03:04 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_manager] Sending command to 192.168.1.38:5555 via adb-shell: (dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)
2019-12-04 12:03:04 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'OPEN\x01\x00\x00\x00\x00\x00\x00\x00\r\x02\x00\x00>\xa8\x00\x00\xb0\xaf\xba\xb1'
2019-12-04 12:03:04 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b"shell:(dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo)\x00"
2019-12-04 12:03:12 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_read(24): b''
2019-12-04 12:03:12 ERROR (SyncWorker_0) [custom_components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: ('Unable to unpack ADB command. (length=0)', b'<6I', b'', error('unpack requires a buffer of 24 bytes'))
2019-12-04 12:03:15 DEBUG (SyncWorker_8) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b"CNXN\x00\x00\x00\x01\x00\x10\x00\x00\x0e\x00\x00\x00'\x05\x00\x00\xbc\xb1\xa7\xb1"
2019-12-04 12:03:15 DEBUG (SyncWorker_8) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'host::hassnuc\x00'
2019-12-04 12:03:24 WARNING (SyncWorker_8) [custom_components.androidtv.androidtv.adb_manager] Couldn't connect to host 192.168.1.38:5555.  TcpTimeoutException: Reading from 192.168.1.38:5555 timed out (9.0 seconds)
2019-12-04 12:03:37 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b"CNXN\x00\x00\x00\x01\x00\x10\x00\x00\x0e\x00\x00\x00'\x05\x00\x00\xbc\xb1\xa7\xb1"
2019-12-04 12:03:37 DEBUG (SyncWorker_0) [custom_components.androidtv.androidtv.adb_shell.adb_device] bulk_write: b'host::hassnuc\x00'
2019-12-04 12:03:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.fire_tv fails
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 104, in connect
    self._adb.connect(rsa_keys=[signer], auth_timeout_s=auth_timeout_s)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/adb_device.py", line 317, in connect
    cmd, arg0, arg1, banner = self._read([constants.AUTH, constants.CNXN], adb_info)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/adb_device.py", line 739, in _read
    msg = self._handle.bulk_read(constants.MESSAGE_SIZE, adb_info.timeout_s)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/tcp_handle.py", line 127, in bulk_read
    return self._connection.recv(numbytes)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/media_player.py", line 271, in _adb_exception_catcher
    return func(self, *args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/media_player.py", line 536, in update
    self._available = self.aftv.adb_connect(always_log_errors=False)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/basetv.py", line 172, in adb_connect
    return self._adb.connect(always_log_errors, auth_timeout_s)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 122, in connect
    self.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 66, in close
    self._adb.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/adb_device.py", line 261, in close
    self._handle.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/tcp_handle.py", line 83, in close
    self._connection.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
2019-12-04 12:03:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.fire_tv fails
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 104, in connect
    self._adb.connect(rsa_keys=[signer], auth_timeout_s=auth_timeout_s)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/adb_device.py", line 308, in connect
    self._handle.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/tcp_handle.py", line 83, in close
    self._connection.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/media_player.py", line 271, in _adb_exception_catcher
    return func(self, *args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/media_player.py", line 536, in update
    self._available = self.aftv.adb_connect(always_log_errors=False)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/basetv.py", line 172, in adb_connect
    return self._adb.connect(always_log_errors, auth_timeout_s)
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 122, in connect
    self.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_manager.py", line 66, in close
    self._adb.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/adb_device.py", line 261, in close
    self._handle.close()
  File "/home/homeassistant/.homeassistant/custom_components/androidtv/androidtv/adb_shell/tcp_handle.py", line 83, in close
    self._connection.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by JeffLIrion** [comment]
Closed by https://github.com/JeffLIrion/adb_shell/pull/54
